import {Patient} from '../shared/types'

export const patients : Patient[] = [
    {
        "id": 1,
        "first_name": "John",
        "surname": "Doe",
        "PPSN": "1234567AB",
        "age": 45,
        "sex": true,
        "personal_phone": 353861234567,
        "emergency_contact_phone": 353851234567,
        "date_most_recently_admitted": "2023-08-10",
        "ailments": ["Back Pain", "Fatigue"],
        "health_conditions": ["Diabetes", "Hypertension"],
        "blood_type": "O+",
        "hospital_visits_count": 5
      },
      {
        "id": 2,
        "first_name": "Jane",
        "surname": "Smith",
        "PPSN": "8765432CD",
        "age": 32,
        "sex": false,
        "personal_phone": 353862345678,
        "emergency_contact_phone": 353852345678,
        "date_most_recently_admitted": "2024-01-15",
        "ailments": ["Migraine"],
        "health_conditions": ["Asthma"],
        "blood_type": "A-",
        "hospital_visits_count": 3
      },
      {
        "id": 3,
        "first_name": "Alice",
        "surname": "O'Brien",
        "PPSN": "1237896EF",
        "age": 27,
        "sex": false,
        "personal_phone": 353861987654,
        "emergency_contact_phone": 353851987654,
        "date_most_recently_admitted": "2022-11-25",
        "ailments": ["Nausea"],
        "health_conditions": ["Anemia"],
        "blood_type": "B+",
        "hospital_visits_count": 2
      },
      {
        "id": 4,
        "first_name": "Michael",
        "surname": "Murray",
        "PPSN": "2345671GH",
        "age": 58,
        "sex": true,
        "personal_phone": 353860123456,
        "emergency_contact_phone": 353850123456,
        "date_most_recently_admitted": "2024-06-05",
        "ailments": ["Joint Pain", "Dizziness"],
        "health_conditions": ["High Cholesterol"],
        "blood_type": "AB-",
        "hospital_visits_count": 8
      },
      {
        "id": 5,
        "first_name": "Emma",
        "surname": "Wilson",
        "PPSN": "8765439IJ",
        "age": 40,
        "sex": false,
        "personal_phone": 353863123789,
        "emergency_contact_phone": 353853123789,
        "date_most_recently_admitted": "2023-05-20",
        "ailments": ["Headache"],
        "health_conditions": ["Anxiety", "Allergy to Penicillin"],
        "blood_type": "A+",
        "hospital_visits_count": 4
      },
      {
        "id": 6,
        "first_name": "Liam",
        "surname": "Nolan",
        "PPSN": "3456721JK",
        "age": 52,
        "sex": true,
        "personal_phone": 353864567890,
        "emergency_contact_phone": 353854567890,
        "date_most_recently_admitted": "2024-02-18",
        "ailments": ["Chest Pain", "Shortness of Breath"],
        "health_conditions": ["Coronary Artery Disease"],
        "blood_type": "B-",
        "hospital_visits_count": 12
      },
      {
        "id": 7,
        "first_name": "Sophie",
        "surname": "Byrne",
        "PPSN": "4567892LM",
        "age": 29,
        "sex": false,
        "personal_phone": 353865678123,
        "emergency_contact_phone": 353855678123,
        "date_most_recently_admitted": "2023-09-30",
        "ailments": ["Fatigue"],
        "health_conditions": ["Iron Deficiency"],
        "blood_type": "O+",
        "hospital_visits_count": 3
      },
      {
        "id": 8,
        "first_name": "Oliver",
        "surname": "Kennedy",
        "PPSN": "5678912NO",
        "age": 37,
        "sex": true,
        "personal_phone": 353862345987,
        "emergency_contact_phone": 353852345987,
        "date_most_recently_admitted": "2024-05-01",
        "ailments": ["Headache", "Insomnia"],
        "health_conditions": ["Migraines", "Seasonal Allergies"],
        "blood_type": "A+",
        "hospital_visits_count": 6
      },
      {
        "id": 9,
        "first_name": "Isabella",
        "surname": "Murphy",
        "PPSN": "7891234PQ",
        "age": 65,
        "sex": false,
        "personal_phone": 353866543210,
        "emergency_contact_phone": 353856543210,
        "date_most_recently_admitted": "2024-07-15",
        "ailments": ["Joint Pain"],
        "health_conditions": ["Osteoarthritis", "Hypertension"],
        "blood_type": "AB+",
        "hospital_visits_count": 15
      },
      {
        "id": 10,
        "first_name": "Noah",
        "surname": "O'Sullivan",
        "PPSN": "8912345RS",
        "age": 23,
        "sex": true,
        "personal_phone": 353867890123,
        "emergency_contact_phone": 353857890123,
        "date_most_recently_admitted": "2022-03-14",
        "ailments": ["Anxiety"],
        "health_conditions": ["Depression"],
        "blood_type": "O-",
        "hospital_visits_count": 2
      },
      {
        "id": 11,
        "first_name": "Charlotte",
        "surname": "Lynch",
        "PPSN": "2345678TU",
        "age": 42,
        "sex": false,
        "personal_phone": 353868765432,
        "emergency_contact_phone": 353858765432,
        "date_most_recently_admitted": "2023-10-08",
        "ailments": ["Cough", "Fever"],
        "health_conditions": ["Asthma", "Seasonal Allergies"],
        "blood_type": "B+",
        "hospital_visits_count": 7
      },
      {
        "id": 12,
        "first_name": "James",
        "surname": "Moore",
        "PPSN": "3456789VW",
        "age": 55,
        "sex": true,
        "personal_phone": 353869123456,
        "emergency_contact_phone": 353859123456,
        "date_most_recently_admitted": "2023-12-22",
        "ailments": ["Shortness of Breath"],
        "health_conditions": ["Chronic Obstructive Pulmonary Disease (COPD)"],
        "blood_type": "A-",
        "hospital_visits_count": 10
      },
      {
        "id": 13,
        "first_name": "Amelia",
        "surname": "Daly",
        "PPSN": "5671234XY",
        "age": 30,
        "sex": false,
        "personal_phone": 353861234654,
        "emergency_contact_phone": 353851234654,
        "date_most_recently_admitted": "2024-01-02",
        "ailments": ["Fatigue", "Dizziness"],
        "health_conditions": ["Anemia"],
        "blood_type": "O+",
        "hospital_visits_count": 4
      },
      {
        "id": 14,
        "first_name": "Ella",
        "surname": "Ryan",
        "PPSN": "6789123ZA",
        "age": 48,
        "sex": false,
        "personal_phone": 353862345876,
        "emergency_contact_phone": 353852345876,
        "date_most_recently_admitted": "2023-11-17",
        "ailments": ["Nausea"],
        "health_conditions": ["Diabetes", "High Blood Pressure"],
        "blood_type": "AB+",
        "hospital_visits_count": 9
      },
      {
        "id": 15,
        "first_name": "Mason",
        "surname": "Walsh",
        "PPSN": "7894561BC",
        "age": 36,
        "sex": true,
        "personal_phone": 353863123098,
        "emergency_contact_phone": 353853123098,
        "date_most_recently_admitted": "2024-04-10",
        "ailments": ["Skin Rash"],
        "health_conditions": ["Eczema"],
        "blood_type": "B-",
        "hospital_visits_count": 5
      }
]